name: score
services:
    pg-unQkBP:
        environment:
            POSTGRES_PASSWORD: HUKXMUlZ3LywfeDe
            POSTGRES_USER: postgres
        healthcheck:
            test:
                - CMD
                - pg_isready
                - -U
                - postgres
            timeout: 2s
            interval: 2s
            retries: 15
        image: postgres:17-alpine
        restart: always
        volumes:
            - type: volume
              source: pg-unQkBP-data
              target: /var/lib/postgresql/data
    pg-unQkBP-init:
        command:
            - -c
            - |
              cd /db-scripts
              ls db-*.sql | xargs cat | psql "postgresql://postgres:$${POSTGRES_PASSWORD}@pg-unQkBP:5432/postgres"
        depends_on:
            pg-unQkBP:
                condition: service_healthy
                restart: true
                required: false
        entrypoint:
            - /bin/sh
        environment:
            POSTGRES_PASSWORD: HUKXMUlZ3LywfeDe
        image: postgres:17-alpine
        labels:
            dev.score.compose.labels.is-init-container: "true"
        volumes:
            - type: bind
              source: .score-compose/mounts/pg-unQkBP-db-scripts
              target: /db-scripts
    service-a-container-id:
        annotations:
            compose.score.dev/workload-name: service-a
        depends_on:
            wait-for-resources:
                condition: service_completed_successfully
                required: true
        environment:
            CONNECTION_STRING: postgresql://user-fECtJCOQ:HUKXMUlZ3LywfeDe@pg-unQkBP:5432
        hostname: service-a
        image: busybox
    wait-for-resources:
        command:
            - echo
        depends_on:
            pg-unQkBP:
                condition: service_healthy
                required: true
            pg-unQkBP-init:
                condition: service_completed_successfully
                required: true
        image: alpine
volumes:
    pg-unQkBP-data:
        driver: local
