SELECT 'CREATE DATABASE "db-PHbTATPz"' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'db-PHbTATPz')\gexec
SELECT $$CREATE USER "user-fECtJCOQ" WITH PASSWORD 'HUKXMUlZ3LywfeDe'$$ WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'user-fECtJCOQ')\gexec
GRANT ALL PRIVILEGES ON DATABASE "db-PHbTATPz" TO "user-fECtJCOQ";
\connect "db-PHbTATPz";
GRANT ALL ON SCHEMA public TO "user-fECtJCOQ";